wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.9
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699032361.242399
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.6.9
      5: 0.15.10
      8:
      - 5
beam_size:
  desc: null
  value: '5'
max_decoding_time_step:
  desc: null
  value: '100'
