wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.9
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699025660.866879
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.6.9
      5: 0.15.10
      8:
      - 5
lr:
  desc: null
  value: '0.005'
batch_size:
  desc: null
  value: '64'
embed_size:
  desc: null
  value: '256'
hidden_size:
  desc: null
  value: '256'
dropout:
  desc: null
  value: '0.2'
input_feed:
  desc: null
  value: true
label_smoothing:
  desc: null
  value: '0.1'
log_every:
  desc: null
  value: '10'
lr_decay:
  desc: null
  value: '0.5'
uniform_init:
  desc: null
  value: '0.1'
max_epoch:
  desc: null
  value: '35'
