wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.9
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700033845.918922
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.6.9
      5: 0.15.10
      8:
      - 5
