wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.9
    cli_version: 0.15.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700033432.533656
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.6.9
      5: 0.15.10
      8:
      - 5
